trainer:
  name: Trainer
  num_epochs: 60
  verbose: 0

model:
  name: cifar_convnet
  num_classes: 10
  image_size: 32

dataset:
  name: CIFAR10DataLoader
  root: ~/.wrt/data
  subset: all
  batch_size: 128
  image_size: 32
  num_workers: 16

optimizer:
  name: Adam
  lr: 0.001


name: convnet
output_dir: outputs/cifar10/random_start/convnet/