trainer:
  name: Trainer
  num_epochs: 120
  verbose: 0

model:
  name: ResNet20_CIFAR10
  num_classes: 10
  image_size: 32
  channels: 3

dataset:
  name: CIFAR10DataLoader
  root: ~/.wrt/data
  subset: all
  batch_size: 128
  image_size: 32
  num_workers: 16

optimizer:
  name: TFRMSprop
#   lr: 0.001
#  momentum: 0.9
#  weight_decay: 0.0001
#  nesterov: True

scheduler:
  name: MultiStepLR
  milestones: [30, 60, 90]
  gamma: 0.2


name: resnet20
output_dir: outputs/cifar10/random_start_models/resnet20/