trainer:
  name: Trainer
  num_epochs: 60
  verbose: 0

model:
  name: VGG16
  num_classes: 10
  image_size: 32

dataset:
  name: CIFAR10DataLoader
  root: ~/.wrt/data
  subset: all
  batch_size: 128
  image_size: 32
  num_workers: 16

optimizer:
  name: Adam
  lr: 0.001

scheduler:
  name: MultiStepLR
  milestones: [20, 35, 50]
  gamma: 0.2

name: VGG16
output_dir: outputs/cifar10/random_start/VGG16/