create:
  name: fine_pruning_attack
  num_classes: 1000
  ratio: 0.04
  layer_index: 15
  layer_name: ['0', '1', '2','3','4','5','6','7', '8', '9','10', '11', '12', '13','14','15']

remove:
  name: fine_pruning_removal
  epochs: 3

dataset:
  name: ImageNetDataLoader
  subset: all
  root: /home/data/data/imagenet
  batch_size: 64
  image_size: 224
  num_workers: 16
  shuffle: False

true_labels: True
name: fine_pruning
output_dir: outputs/imagenet/attacks/fine_pruning/