create:
  name: ftll_attack
  num_classes: 1000

remove:
  name: ftll_removal
  epochs: 1

dataset:
  name: ImageNetDataLoader
  subset: all
  root: /home/data/data/imagenet
  batch_size: 32
  image_size: 224
  num_workers: 16

true_labels: True
name: ftll
output_dir: outputs/imagenet/attacks/ftll/