create:
  name: rtal_attack
  num_classes: 1000

remove:
  name: rtal_removal
#  train_all_params_after_n_batches: 200
#  layer_bounds: [ 51, 158, -1 ]
#  layer_lrs: [0.0001, 0.0001, 0.1]
  epochs: 10

dataset:
  name: ImageNetDataLoader
  subset: all
  root: /home/data/data/imagenet
  batch_size: 32
  image_size: 224
  num_workers: 16

scheduler:
  name: MultiStepLR
  milestones: [3,6,9]
  gamma: 0.1

optimizer:
  name: Adam
  lr: 0.001

true_labels: True
name: rtal
output_dir: outputs/imagenet/attacks/rtal/