create:
  name: rtll_attack
  num_classes: 1000

remove:
  name: rtll_removal
  lr: 0.01
  epochs: 20

dataset:
  name: ImageNetDataLoader
  subset: all
  root: /home/data/data/imagenet
  batch_size: 128
  image_size: 224
  num_workers: 16

scheduler:
  name: MultiStepLR
  milestones: [5,10,15]
  gamma: 0.1

optimizer:
  name: TFRMSprop
  lr: 0.01

true_labels: True
name: rtll
output_dir: outputs/imagenet/attacks/rtll/