trainer:
  name: Trainer
  num_epochs: 60
  verbose: 0

model:
  name: gtsrb_convnet
  num_classes: 43
  image_size: 32

dataset:
  name: GTSRBDataLoader
  root: /home/data/data/gtsrb
  subset: all
  # batch_size: 128
  batch_size: 32
  image_size: 32
  num_workers: 16

optimizer:
  name: TFRMSprop
#   lr: 0.001
#  momentum: 0.9
#  weight_decay: 0.0001
#  nesterov: True

scheduler:
  name: MultiStepLR
  milestones: [20, 35, 50]
  gamma: 0.2


name: convnet
output_dir: outputs/gtsrb/random_start/convnet/