trainer:
  name: Trainer
  num_epochs: 60
  verbose: 0

model:
  name: LeNet5
  num_classes: 10
  image_size: 28
  channels: 1

dataset:
  name: MNISTDataLoader
  root: /home/data/data/mnist
  subset: all
  # batch_size: 128
  batch_size: 256
  image_size: 28
  num_workers: 16

optimizer:
  name: TFRMSprop
#   lr: 0.001
#  momentum: 0.9
#  weight_decay: 0.0001
#  nesterov: True

scheduler:
  name: MultiStepLR
  milestones: [20, 35, 50]
  gamma: 0.2


name: Lenet5
output_dir: outputs/mnist/random_start/Lenet5/