create:
  name: ftll_attack
  num_classes: 10
  # lr: 0.00001

remove:
  name: ftll_removal
  epochs: 5

dataset:
  name: MNISTDataLoader
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 28
  num_workers: 2

true_labels: True
name: ftll
output_dir: outputs/mnist/attacks/ftll/