create:
  name: weight_quantization_attack

remove:
  name: weight_quantization_removal
  epochs: 1
  bits: 5

dataset:
  name: GTSRBDataLoader
  subset: all
  root: /home/data/data/gtsrb
  batch_size: 64
  image_size: 32
  num_workers: 2

true_labels: True
name: weight_quantization
output_dir: outputs/gtsrb/attacks/weight_quantization/