create:
  name: fzll_attack
  num_classes: 10
  # lr: 0.00001

remove:
  name: fzll_removal
  epochs: 5

dataset:
  name: CIFAR10DataLoader
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 32
  num_workers: 2

true_labels: True
name: fzll
output_dir: outputs/cifar10/attacks/fzll/