create:
  name: rtll_attack
  num_classes: 10

remove:
  name: rtll_removal
  epochs: 20

dataset:
  name: CIFAR10DataLoader
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 32
  num_workers: 2

optimizer:
  name: Adam
  lr: 0.001

scheduler:
  name: MultiStepLR
  milestones: [ 5, 10, 15 ]
  gamma: 0.2


true_labels: True
name: rtll
output_dir: outputs/cifar10/attacks/rtll/